name: Build EXE for Windows 7

on:
  workflow_dispatch:  # Ручной запуск через кнопку
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-2019
    timeout-minutes: 30  # Чтобы не слетало по времени
    
    steps:
    # 1. Загружаем код
    - name: Checkout
      uses: actions/checkout@v4  # Только так работает в 2024!
    
    # 2. Ставим Python 3.4.4 (32-bit)
    - name: Install Python
      run: |
        $url = "https://www.python.org/ftp/python/3.4.4/python-3.4.4.msi"
        $path = "$env:TEMP\python.msi"
        Invoke-WebRequest $url -OutFile $path
        Start-Process msiexec.exe -Wait -ArgumentList "/i $path /quiet"
        echo "C:\Python34;C:\Python34\Scripts" >> $env:GITHUB_PATH
    
    # 3. Ставим нужные библиотеки
    - name: Install tools
      run: |
        python -m pip install --upgrade pip==9.0.3
        pip install pyinstaller==3.6 ezdxf==0.17.2
    
    # 4. Собираем EXE
    - name: Build EXE
      run: |
        pyinstaller --onefile --noconsole --icon=IMG_8028.ico GovnaPiroga.py
    
    # 5. Загружаем результат
    - name: Upload EXE
      uses: actions/upload-artifact@v4  # Обязательно v4!
      with:
        name: GovnaPiroga_Win7
        path: dist/GovnaPiroga.exe
