name: Build GovnaPiroga for Windows 7 x86

on:
  push:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  build:
    name: Build EXE for Win7 x86
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: ["3.7"]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify icon exists (PowerShell)
        shell: pwsh
        run: |
          if (-not (Test-Path "IMG_8028.ico")) {
            Write-Error "Icon file IMG_8028.ico not found!"
            exit 1
          }

      - name: Set up Python 3.7 (32-bit)
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x86

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller==4.10 ezdxf==0.17.2

      - name: Build EXE
        run: |
          pyinstaller `
            --onefile `
            --windowed `
            --name GovnaPiroga_Win7 `
            --icon=IMG_8028.ico `
            GovnaPiroga.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GovnaPiroga_Win7
          path: dist/GovnaPiroga_Win7.exe
