name: Build 32-bit EXE
on: [push]

jobs:
  build:
    runs-on: windows-2019  # Важно для Python 3.7
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Python 3.7.9 (32-bit)
        uses: actions/setup-python@v2
        with:
          python-version: "3.7.9"
          architecture: "x86"  # Ключевая строка!

      - name: Install PyInstaller
        run: pip install pyinstaller==4.10

      - name: Build 32-bit EXE
        run: |
          pyinstaller `
            --onefile `
            --noconsole `
            --icon=IMG_8028.ico `
            GovnaPiroga.py

      - uses: actions/upload-artifact@v4
        with:
          name: GovnaPiroga_32bit
          path: dist/GovnaPiroga.exe
