name: Build COXOproScan (Windows x86)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.7 (x86)
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
          architecture: "x86"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller==4.10 ezdxf==0.17.2

      - name: Prepare DLLs
        shell: cmd
        run: |
          @echo Полный путь к Python:
          where python
          
          @echo Копируем необходимые DLL...
          xcopy /Y "C:\hostedtoolcache\windows\Python\3.7.9\x86\python37.dll" .
          xcopy /Y "C:\hostedtoolcache\windows\Python\3.7.9\x86\DLLs\tcl86t.dll" .
          xcopy /Y "C:\hostedtoolcache\windows\Python\3.7.9\x86\DLLs\tk86t.dll" .
          
          @echo Проверяем наличие файлов:
          dir *.dll

      - name: Build EXE
        shell: cmd
        run: |
          pyinstaller ^
            --onefile ^
            --windowed ^
            --name COXOproScan ^
            --icon=IMG_8084.ico ^
            --paths "C:\hostedtoolcache\windows\Python\3.7.9\x86\DLLs" ^
            --add-binary "python37.dll;." ^
            --add-binary "tcl86t.dll;." ^
            --add-binary "tk86t.dll;." ^
            GovnaPiroga.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: COXOproScan-Win7-Full
          path: dist/COXOproScan.exe
