name: Build GovnaPiroga for Windows 7 x86

on:
  push:
    branches:  # Запуск при пуше в любую ветку
      - main
      - master
      - develop
  workflow_dispatch:  # Ручной запуск

jobs:
  build:
    name: Build EXE for Win7 x86
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: ["3.7"]  # Python 3.7 x86
    
    steps:
      - name: Checkout code (включая иконку)
        uses: actions/checkout@v2

      - name: Set up Python 3.7 (32-bit)
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x86

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller==4.10 ezdxf==0.17.2 tkinter

      - name: Build EXE with PyInstaller (с иконкой)
        run: |
          pyinstaller \
            --onefile \
            --windowed \
            --name GovnaPiroga_Win7 \
            --icon=IMG_8028.ico \  # Указываем вашу иконку
            GovnaPiroga.py  # Собираем ваш основной файл

      - name: Upload artifact (EXE)
        uses: actions/upload-artifact@v2
        with:
          name: GovnaPiroga_Win7
          path: dist/GovnaPiroga_Win7.exe
