name: Build COXOproScan (Windows x86)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.7 (x86)
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
          architecture: "x86"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller==4.10 ezdxf==0.17.2 pillow==9.5.0

      - name: Prepare resources
        shell: cmd
        run: |
          python -c "from PIL import Image; img = Image.open('IMG_8084.ico'); print(f'Icon sizes: {img.size}')"
          copy "C:\hostedtoolcache\windows\Python\3.7.9\x86\python37.dll" .
          copy "C:\hostedtoolcache\windows\Python\3.7.9\x86\DLLs\tcl86t.dll" .
          copy "C:\hostedtoolcache\windows\Python\3.7.9\x86\DLLs\tk86t.dll" .

      - name: Build EXE
        shell: cmd
        run: |
          pyinstaller ^
            --onefile ^
            --windowed ^
            --name COXOproScan ^
            --icon=IMG_8084.ico ^
            --add-data "IMG_8084.ico;." ^
            --paths "C:\hostedtoolcache\windows\Python\3.7.9\x86\DLLs" ^
            --add-binary "python37.dll;." ^
            --add-binary "tcl86t.dll;." ^
            --add-binary "tk86t.dll;." ^
            --runtime-tmpdir . ^
            --noconfirm ^
            --clean ^
            GovnaPiroga.py

      - name: Verify EXE
        shell: cmd
        run: |
          dir "dist\COXOproScan.exe"
          python -c "import os; print(f'EXE size: {os.path.getsize(r\"dist\\COXOproScan.exe\") // 1024} KB')"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: COXOproScan-Windows
          path: dist/COXOproScan.exe
          retention-days: 7
