name: Build EXE

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Python 3.4
        run: |
          Invoke-WebRequest https://www.python.org/ftp/python/3.4.4/python-3.4.4.msi -OutFile python.msi
          Start-Process msiexec.exe -Wait -ArgumentList '/i python.msi /quiet'
          echo "C:\Python34;C:\Python34\Scripts" >> $env:GITHUB_PATH
          
      - name: Install PyInstaller
        run: |
          python -m pip install pyinstaller==3.6
          
      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole --icon=IMG_8028.ico GovnaPiroga.py
          
      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: MyApp
          path: dist/GovnaPiroga.exe
