name: Build GovnaPiroga (Win7 Stable)
on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4

      - name: Install Python 3.7.9 (32-bit)
        uses: actions/setup-python@v2
        with:
          python-version: "3.7.9"
          architecture: "x86"

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller==4.10

      - name: Download required DLLs
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://www.dll-files.com/download/api-ms-win-crt-runtime-l1-1-0.dll.html" -OutFile "api-ms-win-crt-runtime-l1-1-0.dll"
          Invoke-WebRequest -Uri "https://www.dll-files.com/download/vcruntime140.dll.html" -OutFile "vcruntime140.dll"
          # Для python37.dll используем системный файл
          Copy-Item "C:\Python37\python37.dll" -Destination "."

      - name: Build EXE (Safe Mode)
        shell: cmd
        run: |
          pyinstaller --onefile ^
            --noconsole ^
            --icon=IMG_8028.ico ^
            --add-data "IMG_8028.ico;." ^
            --add-binary "api-ms-win-crt-runtime-l1-1-0.dll;." ^
            --add-binary "vcruntime140.dll;." ^
            --add-binary "python37.dll;." ^
            --paths "C:\Python37" ^
            --clean ^
            GovnaPiroga.py

      - uses: actions/upload-artifact@v4
        with:
          name: GovnaPiroga_Win7_Final
          path: dist/GovnaPiroga.exe
