name: Build IvanorProScan (Windows x86)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.7 (x86)
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
          architecture: "x86"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller==4.10 ezdxf==0.17.2

      - name: Build EXE with all DLLs
        shell: cmd  # Явно указываем использовать CMD вместо PowerShell
        run: |
          xcopy /Y "C:\Python37\DLLs\*.*" ".\"
          pyinstaller --onefile --windowed --name IvanorProScan --icon=IMG_8028.ico --add-data "*.dll;." --add-data "venv\Lib\site-packages\ezdxf;ezdxf" GovnaPiroga.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: IvanorProScan-Win7-Full
          path: dist/IvanorProScan.exe
