name: Build EXE for Windows 7 SP1 x86

on: push

jobs:
  build:
    runs-on: windows-2019
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    # Установка Python 3.4.4
    - name: Install Python
      run: |
        # Скачиваем и устанавливаем Python
        Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.4.4/python-3.4.4.msi" -OutFile "python34.msi"
        Start-Process -Wait -FilePath "msiexec.exe" -ArgumentList "/i python34.msi /quiet"
        
        # Добавляем Python в PATH
        $pythonPath = "C:\Python34"
        $env:PATH = "$pythonPath;$env:PATH"
        echo "$pythonPath" >> $env:GITHUB_PATH

    # Установка зависимостей
    - name: Install dependencies
      run: |
        # Проверяем, что Python доступен
        python --version
        
        # Устанавливаем pip
        python -m ensurepip --default-pip
        python -m pip install --upgrade "pip==9.0.3"
        
        # Устанавливаем необходимые пакеты
        python -m pip install "pypiwin32==219" "pywin32-ctypes==0.2.0"
        
        # Устанавливаем PyInstaller
        python -m pip install "https://github.com/pyinstaller/pyinstaller/archive/v3.6.zip"

    # Сборка EXE
    - name: Build EXE
      run: |
        python -m PyInstaller --onefile --noconsole --icon=IMG_8028.ico GovnaPiroga.py

    # Выгрузка результата
    - uses: actions/upload-artifact@v4
      with:
        name: GovnaPiroga_Win7
        path: dist/GovnaPiroga.exe
