name: Build GovnaPiroga (Win7 x86 - Final)
on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4

      - name: Download DLLs from trusted sources
        shell: powershell
        run: |
          # Скачиваем VC++ DLL из официального дистрибутива Microsoft
          Invoke-WebRequest -Uri "https://aka.ms/vs/16/release/vc_redist.x86.exe" -OutFile vc_redist.exe
          Start-Process -Wait -FilePath .\vc_redist.exe -ArgumentList "/q /extract" -NoNewWindow
          Copy-Item -Path "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Redist\MSVC\14.29.30133\vcruntime140.dll" -Destination .
          
          # Скачиваем python37.dll из официального инсталлятора Python
          Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.7.9/python-3.7.9-embed-win32.zip" -OutFile python.zip
          Expand-Archive -Path python.zip -DestinationPath python_temp
          Copy-Item -Path "python_temp\python37.dll" -Destination .

      - name: Set up Python 3.7.9 (32-bit)
        uses: actions/setup-python@v2
        with:
          python-version: "3.7.9"
          architecture: "x86"

      - name: Install PyInstaller
        run: pip install pyinstaller==4.10

      - name: Build EXE
        shell: cmd
        run: |
          pyinstaller --onefile ^
            --noconsole ^
            --icon=IMG_8028.ico ^
            --add-data "IMG_8028.ico;." ^
            --add-binary "vcruntime140.dll;." ^
            --add-binary "python37.dll;." ^
            --hidden-import=tkinter ^
            --hidden-import=csv ^
            --clean ^
            GovnaPiroga.py

      - uses: actions/upload-artifact@v4
        with:
          name: GovnaPiroga_Final
          path: dist/GovnaPiroga.exe
