name: Build EXE

on: push  # Автосборка при любом push

jobs:
  build:
    runs-on: windows-2019
    
    steps:
    # 1. Копируем файлы проекта
    - uses: actions/checkout@v4
    
    # 2. Устанавливаем Python 3.4.4 (официальный установщик)
    - name: Install Python 3.4
      run: |
        Invoke-WebRequest https://www.python.org/ftp/python/3.4.4/python-3.4.4.msi -OutFile python34.msi
        Start-Process msiexec.exe -Wait -ArgumentList '/i python34.msi /quiet'
        echo "C:\Python34;C:\Python34\Scripts" >> $env:GITHUB_PATH
    
    # 3. Собираем EXE (PyInstaller уже встроен в Python 3.4)
    - name: Build EXE
      run: |
        C:\Python34\python.exe -m PyInstaller --onefile --noconsole --icon=IMG_8028.ico GovnaPiroga.py
    
    # 4. Выдаём готовый файл
    - uses: actions/upload-artifact@v4
      with:
        name: GovnaPiroga_Win7.exe
        path: dist/GovnaPiroga.exe
