name: Build EXE for Windows 7

on: push

jobs:
  build:
    runs-on: windows-2019
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    # Установка Python 3.4.4
    - name: Install Python 3.4
      run: |
        Invoke-WebRequest https://www.python.org/ftp/python/3.4.4/python-3.4.4.msi -OutFile python34.msi
        Start-Process msiexec.exe -Wait -ArgumentList '/i python34.msi /quiet'
        echo "C:\Python34;C:\Python34\Scripts" >> $env:GITHUB_PATH

    # Установка всех зависимостей ВРУЧНУЮ
    - name: Install dependencies
      run: |
        # Скачиваем и устанавливаем ВСЕ зависимости вручную
        python -m pip install "https://files.pythonhosted.org/packages/1e/9a/31e9e5b4a7505e2871a7d9a1f7023f1b0b518a0e4f1e9b85c6a61f5eb0d2/altgraph-0.10.2-py2.py3-none-any.whl"
        python -m pip install "https://files.pythonhosted.org/packages/3c/b9/0b3159f5e2c7b8c5b9e3d7b5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5/pefile-2016.3.28.tar.gz"
        python -m pip install "https://files.pythonhosted.org/packages/3c/b9/0b3159f5e2c7b8c5b9e3d7b5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5/pypiwin32-219-cp34-none-win32.whl"
        python -m pip install "https://github.com/pyinstaller/pyinstaller/archive/v3.6.zip"

    # Сборка EXE
    - name: Build EXE
      run: |
        python -m PyInstaller --onefile --noconsole --icon=IMG_8028.ico GovnaPiroga.py

    # Выгрузка результата
    - uses: actions/upload-artifact@v4
      with:
        name: GovnaPiroga_Win7
        path: dist/GovnaPiroga.exe
