name: Build GovnaPiroga (Win7 Final)
on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4

      - name: Install Python 3.7.9 (32-bit)
        uses: actions/setup-python@v2
        with:
          python-version: "3.7.9"
          architecture: "x86"

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller==4.10

      - name: Download DLLs from reliable source
        shell: cmd
        run: |
          curl -L https://github.com/nalexandru/api-ms-win-core-path-HACK/releases/download/0.3.1/api-ms-win-crt-runtime-l1-1-0.dll --output api-ms-win-crt-runtime-l1-1-0.dll
          curl -L https://raw.githubusercontent.com/nalexandru/api-ms-win-core-path-HACK/master/vcruntime140.dll --output vcruntime140.dll
          copy "C:\Python37\python37.dll" .

      - name: Prepare Tkinter
        shell: cmd
        run: |
          xcopy "C:\Python37\tcl" "tcl\" /E /I /Y
          xcopy "C:\Python37\Lib\tkinter" "tkinter\" /E /I /Y
          copy "C:\Python37\DLLs\_tkinter.pyd" .

      - name: Build EXE
        shell: cmd
        run: |
          pyinstaller --onefile ^
            --noconsole ^
            --icon=IMG_8028.ico ^
            --add-data "IMG_8028.ico;." ^
            --add-data "tcl;tcl" ^
            --add-data "tkinter;tkinter" ^
            --add-binary "_tkinter.pyd;." ^
            --add-binary "api-ms-win-crt-runtime-l1-1-0.dll;." ^
            --add-binary "vcruntime140.dll;." ^
            --add-binary "python37.dll;." ^
            --hidden-import tkinter ^
            --clean ^
            GovnaPiroga.py

      - uses: actions/upload-artifact@v4
        with:
          name: GovnaPiroga_Win7_Complete
          path: dist/GovnaPiroga.exe
