name: Build GovnaPiroga EXE (Windows 7 compatible)
on: [push]

jobs:
  build:
    runs-on: windows-latest  # Сборка на Windows!
    steps:
      - uses: actions/checkout@v4

      - name: Install Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"  # Ключевое изменение!

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller==4.10  # Последняя стабильная для Python 3.7

      - name: Build EXE
        run: |
          pyinstaller \
            --onefile \
            --noconsole \
            --icon=IMG_8028.ico \
            --hidden-import=tkinter \
            --collect-all tkinter \
            --add-data "IMG_8028.ico;." \
            GovnaPiroga.py

      - uses: actions/upload-artifact@v4
        with:
          name: GovnaPiroga_Win7_EXE
          path: dist/GovnaPiroga.exe
