name: Build Windows 7 EXE

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-2019
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Python 3.4.4 (32-bit)
      run: |
        $pythonUrl = "https://www.python.org/ftp/python/3.4.4/python-3.4.4.msi"
        $installerPath = "$env:TEMP\python-3.4.4.msi"
        Invoke-WebRequest -Uri $pythonUrl -OutFile $installerPath
        Start-Process -Wait -FilePath "msiexec.exe" -ArgumentList "/i $installerPath /quiet"
        Add-Content $env:GITHUB_PATH "C:\Python34;C:\Python34\Scripts"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip==9.0.3
        pip install -r requirements.txt
        
    - name: Build EXE
      run: |
        pyinstaller --onefile --noconsole --icon=IMG_8028.ico GovnaPiroga.py
        
    - name: Upload EXE
      uses: actions/upload-artifact@v2
      with:
        name: GovnaPiroga-Win7
        path: dist/GovnaPiroga.exe
